In [1]:
import numpy as np

In [2]:
def load_rewards(file_name):
    f = open(file_name, 'r')
    rewards = [int(line.strip('\n')) for line in f.readlines()]
    return rewards

In [3]:
def load_matrix(file_name):
    matrix = np.zeros((81, 81))
    f = open(file_name, 'r')
    for i in f.readlines():
        i = i.split()
        matrix[int(i[0]) - 1][int(i[1]) - 1] = float(i[2])
    return matrix

In [4]:
rewards = load_rewards('rewards.txt')
rewards = np.matrix(rewards).reshape(81, 1)

m1 = load_matrix('prob_a1.txt')
m2 = load_matrix('prob_a2.txt')
m3 = load_matrix('prob_a3.txt')
m4 = load_matrix('prob_a4.txt')
action_all = [m1, m2, m3, m4]

In [5]:
N = len(m1[0])
decay = 0.99

In [6]:
def max_v_a(action, s, prev_v):
    max_v = float('-inf')
    max_a = -1
    for i in range(4):
        vp = 0
        for k in range(N):
            vp += action[i][s][k] * prev_v[k]
        if vp > max_v:
            max_v = vp
            max_a = i
    return max_v, max_a

In [7]:
p = np.zeros(N)
value = np.zeros(N)

In [8]:
for _ in range(50):
    pp = np.zeros((N, N))
    for i in range(N):
        a = p[i]
        pp[i] = action_all[int(a)][i]

    prev_v = np.matrix(np.identity(N) - decay * pp).getI() * rewards

    for i in range(N):
        max_v, max_a = max_v_a(action_all, i, prev_v)
        value[i] = rewards[i][0] + decay * max_v
        p[i] = max_a

In [10]:
v1 = value.reshape(9,9).T

In [17]:
for i in range(9):
    for j in range(9):
        v1[i][j] = round(v1[i][j])

In [18]:
v1

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,   66.,   67.,   78.,   80.,   72., -100.,    0.,  100.],
       [   0.,   56., -100.,   70.,   81.,   83.,   85.,   97.,   99.],
       [   0.,   55.,   50.,   60.,    0.,   81.,    0.,   97.,   99.],
       [  54.,   54.,    0., -100., -100.,   62., -100.,   88.,  100.],
       [   0.,   53.,   44.,   51.,   61.,   72.,   74.,   85.,   98.],
       [   0.,   44., -100.,    0.,    0.,   70.,    0., -100.,   88.],
       [   0.,   48.,   49.,   58.,   59.,   60., -100.,    0.,  100.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]])

In [19]:
p.reshape(9,9).T

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  2.,  2.,  3.,  3.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  2.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  1.,  2.,  1.,  0.,  1.,  0.,  2.,  3.],
       [ 2.,  1.,  0.,  0.,  0.,  1.,  0.,  2.,  0.],
       [ 0.,  1.,  0.,  2.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  3.],
       [ 0.,  2.,  2.,  2.,  2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [20]:
p = np.zeros(N)
value = np.zeros(N)

In [22]:
for _ in range(50):
    prev_v = value
    for i in range(N):
        max_v, max_a = max_v_a(action_all, i, prev_v)
        value[i] = rewards[i][0] + decay * max_v
        p[i] = max_a

In [23]:
v2 = value.reshape(9,9).T

In [24]:
for i in range(9):
    for j in range(9):
        v2[i][j] = round(v2[i][j])

In [25]:
v2

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  22.,  23.,  27.,  28.,  26., -39.,   0.,  39.],
       [  0.,  18., -39.,  25.,  30.,  31.,  32.,  37.,  39.],
       [  0.,  18.,  17.,  21.,   0.,  30.,   0.,  37.,  38.],
       [ 17.,  17.,   0., -39., -39.,  23., -39.,  34.,  39.],
       [  0.,  17.,  14.,  18.,  22.,  27.,  28.,  33.,  38.],
       [  0.,  14., -39.,   0.,   0.,  26.,   0., -39.,  34.],
       [  0.,  16.,  17.,  21.,  21.,  22., -39.,   0.,  39.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [26]:
p.reshape(9,9).T

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  2.,  2.,  3.,  3.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  2.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  1.,  2.,  1.,  0.,  1.,  0.,  2.,  3.],
       [ 2.,  1.,  0.,  0.,  0.,  1.,  0.,  2.,  0.],
       [ 0.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  3.],
       [ 0.,  2.,  2.,  2.,  2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])